# Notations
1. $\mathbb{R}$ is the set of real numbers. elements look like $1,2,-1,\pi,\sqrt{2},5.2,etc$
2. $\mathbb{R}^2$ is the set of 2 tuples from $\mathbb{R}$. Elements look like $(0,0),(1,3),(3,\sqrt{7}), etc.$
3. $\mathbb{R}^n$ is the set of $n$ (here $n$ can be any natural number) tuples from $\mathbb{R}$


# Libraries
Libraries contain some standard packages of function which helps to avoid writing repeatative codes and makes calculation faster.
Inorder to use libraries one needs to import them
### 1. Numpy 
**This** library is very useful, one can check the inbuilt fubctions numpy contaion by writing the codes as given below

In [19]:
import numpy#importing the library numpy
print(dir(numpy))
print(len(dir(numpy)))
#One can also check the same for other libraries (pandas,scipy,etc)

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

### Vectors
We usually treat vectors as tuples/row vector/ column vector/ coordinates to do calculations
For instance $v=(1,1,2)$ is a vector  in $\mathbb{R}^3$.
We can say polynomial functions such as $x^2+2x+1$ is also a vector and we would like it to be seen as $(1,2,1)$ more pricisely (coefficient of $x^2$,coefficient of $x^1$,coefficient of $x^0$

## Scalar Multiplication

Let $\alpha$ be a scalar and $v$ be any vector then $\alpha\cdot v$ is a scalar multiplication. Equivalently the vector $v$ is said to be scaled by the factor $\alpha$

for example $\alpha=3$ is a scalar and $v=(2,3,5)$ is a vector then we can compute $\alpha\cdot v$ as
$$3\cdot (2,3,5)=(3\times2,3\times3,3\times5)=(6,9,15)$$

In [1]:
x=[2,3,5]
for i in range (3):
      x[i]=3*x[i]
x


[6, 9, 15]

# Vector dot product

In vector dot product we take two vectors together to find a value teremed as the dot product.
For example
$v_1 \text{ and } v_2$ are two vectors and while dealing with vectors as coordinate vectors we prefer multiplying coordinates of $v_1$ to corresponding coordinates of $v_2$
Note:There are many other forms of inner product which brings various other geometric interpretibilities.

In [3]:
#Finding the dot product of two vectors v_1=(1,2,3,4) and v_2=(3,1,2,1) using for loop
z=[0,0,0,0] #initializing z for getting dot product
v_1=[1,2,3,4] 
v_2=[3,1,2,1]
for i in range (4) :
    z[i]=v_1[i]*v_2[i]
w=z[0]+z[1]+z[2]+z[3]
print(w)

15


In [2]:
#Using numpy to find dot product
import numpy as np
v_1=[1,2,3,4] 
v_2=[3,1,2,1]
np.dot(v_1,v_2)

15

Note: it is not useful to use tuples as they are immutable.

# Special Vectors

1. Zero vector
usually rpresented as the symbol 0, represents to a unique vector in the space that never alters the vector to which it is added.
$(0,0,0)$ is the zero vector in $\mathbb{R}^3$

2. Unit Vectors are special class of vector that have a length equal to unity. For example:
$$(1,0,0),(0,1,0),(0,0,1),\left(\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}}\right),etc.$$

# Dimension of a vector
A vector is said $n$ dimentional if it has $n$ coordinates.
$(0,0,0) $ is a 3 dimentional vector.
The first entry is said to be 1st coordinate correspondingly the last coordinate is said to be the n-th coordintae.
One can implement python to check number of coordinates a vector has and print its dimention

In [41]:
#Identifying the dimentions of vectors v_1=(1,2,1),v_2=(3,2),v_3=(1,2,1,2,1,2,3,88), v_4=(0,0,0,0)
v_1=[1,2,1]
v_2=[3,2]
v_3=[1,2,1,2,1,2,3,88]
v_4=[0,0,0,0]
print("Dimention of v_1 is:",len(v_1))
print("Dimention of v_2 is:",len(v_2))
print("Dimention of v_3 is:",len(v_3))
print("Dimention of v_4 is:",len(v_4))


Dimention of v_1 is: 3
Dimention of v_2 is: 2
Dimention of v_3 is: 8
Dimention of v_4 is: 4


# Geometry and visualization for dimention
In geometry one can visualize one dimention as the real line, 2 dimention as the 2-D plane, 3-D as the Space.


In [43]:
# import image module 
from IPython.display import Image 

# get the image 
Image(url="/home/srmap/Downloads/geogebra-export.png", width=300, height=300) 


In [45]:
# import image module 
from IPython.display import Image 

# get the image 
Image(url="/home/srmap/Downloads/geogebra-export(1).png", width=300, height=300) 


In [48]:
# import image module 
from IPython.display import Image 

# get the image 
Image(url="/home/srmap/Downloads/geogebra-export(2).png", width=300, height=300) 


## Basic vector operations
# Vector-vector addition
Vector addition is only defined for vectors of same size.
The symbol used is $+$

$$ \begin{align}
x+y=
     \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{m}
         \end{bmatrix}
         +
          \begin{bmatrix}
           y_{1} \\
           y_{2} \\
           \vdots \\
           y_{m}
         \end{bmatrix}
         = \begin{bmatrix}
           x_{1}+y_1 \\
           x_{2}+y_2 \\
           \vdots \\
           x_{m}+y_m
         \end{bmatrix}
  \end{align} $$
  

For instance we need to add $x=(1,2,1),y=(1,-1,1)$ as
$$ \begin{align}
x+y=
     \begin{bmatrix}
           1 \\
           2 \\
           1 
         \end{bmatrix}
         +
          \begin{bmatrix}
           1 \\
           -1 \\
           1
         \end{bmatrix}
         = \begin{bmatrix}
           1+1\\
           2+(-1) \\
           1+1
         \end{bmatrix}
         =\begin{bmatrix}
           2\\
           1 \\
           2
         \end{bmatrix}
  \end{align} $$
  

In [60]:
# 
x_plus_y=[0,0,0]
b=[1,2,1]
c=[1,-1,1]
for i in range (3):
    x_plus_y[i]=b[i]*c[i]
print(x_plus_y)

[1, -2, 1]


# Multiplication of Vector by scalar
A vector can be multiplied with a scalar to obtain another vector. We use the symbol $\cdot$
This means for every sclar $\alpha$ and vector $v$ we can assign a vector $u=\alpha\cdot u$

To obtain zero vector we need to multiply the scalar 0 with the vector.
Vector-scalar multiplication is defined as:
$$ \begin{align}
\alpha\cdot x=\alpha\cdot
     \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{m}
         \end{bmatrix}
         = \begin{bmatrix}
           \alpha\cdot x_{1} \\
           \alpha\cdot x_{2} \\
           \vdots \\
           \alpha\cdot x_{m}
         \end{bmatrix}
  \end{align} $$
  
 For instance we need to find the scalar-vector multiplication of $\alpha=2$ and $x=(1,2,1)$ 
  $$ \begin{align}
\alpha\cdot x=2\cdot
     \begin{bmatrix}
           1 \\
           2 \\
           1
         \end{bmatrix}
         = \begin{bmatrix}
           2\cdot 1 \\
           2\cdot 2 \\
           2\cdot 1
         \end{bmatrix}
         =  \begin{bmatrix}
           2\\
           4 \\
           2
         \end{bmatrix}
  \end{align} $$

In [62]:
# Scalar Vector multiplication
x=[1,2,1]
alpha=2
for i in range (3):
    x[i]=2*x[i]
print(x)

[2, 4, 2]


In [63]:
#Using numpy
x=np.array([[1],[2],[1]])
2*x

array([[2],
       [4],
       [2]])

## Vector Space
Let $V$ be a nonempty set and $F$ be a field (usually we would use $\mathbb{R}$) along with vector addition and scalar multiplication, then we say $(V,F,+,\cdot)$ is a vector space if the following axioms is satisfied:
1. Associativity of vector addition: $u+(v+w)=(u+v)+w$
2. Commutativity of vector addition: $u+v=v+u$
3. Existance of "identity element": There exists an element 0 ∈ V, called the zero vector, such that $v+0=v$ for all $v\in V$
4. Existance of inverse: For every $v \in V$, there exists an element $−v\in V$, called the additive inverse of $v$, such that $v+(−v)= 0$
5. Compatibility of scalar multiplication with field multiplication:$a\cdot(b\cdot v)=(a\cdot b)\cdot v$
6. Identity element of scalar multiplication:$1\cdot v=v$, where $1$ denotes the multiplicative identity in $F$
7. Distributivity of scalar multiplication with respect to vector addition:	$a\cdot (u+v)=a\cdot u+a\cdot v$
8. Distributivity of scalar multiplication with respect to field addition: $(a+b)\cdot v=a\cdot v+b\cdot v$


In [57]:
# using the inbuilt feature for array
import numpy as np
x=np.array([[1],[2],[11]])
x

array([[ 1],
       [ 2],
       [11]])

In [58]:
x.shape

(3, 1)

In [3]:
#The output says the dimention 3*1 that is three rows and 1 columns

In [12]:
#writing a 3*3 matrix\
import numpy as np
x=np.array([[1,2,3],[3,2,1],[1,2,1]])
x

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 1]])

In [24]:
#extacting the entries of the matrix 
import numpy as np
x=np.array([[1,2,3],[3,2,1],[1,2,1]])
for i in range (3):
    for j in range (3):
        a=x[i][j]
        print(a)

1
2
3
3
2
1
1
2
1


In [26]:
#Matrix multiplication
import numpy as np
x=np.array([[1,2,3],[3,2,1],[1,2,1]])
y=np.array([[1,1,2],[1,2,1],[1,2,2]])
z=np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range (3):
    for j in range (3):
        z[i][j]=x[i][j]*y[i][j]
        print(z)

[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 0]
 [0 0 0]
 [0 0 0]]
[[1 2 6]
 [0 0 0]
 [0 0 0]]
[[1 2 6]
 [3 0 0]
 [0 0 0]]
[[1 2 6]
 [3 4 0]
 [0 0 0]]
[[1 2 6]
 [3 4 1]
 [0 0 0]]
[[1 2 6]
 [3 4 1]
 [1 0 0]]
[[1 2 6]
 [3 4 1]
 [1 4 0]]
[[1 2 6]
 [3 4 1]
 [1 4 2]]


In [27]:
import numpy as np
x=np.array([[1,2,3],[3,2,1],[1,2,1]])
y=np.array([[1,1,2],[1,2,1],[1,2,2]])
z=np.array([[0,0,0],[0,0,0],[0,0,0]])
np.x*y

<class 'AttributeError'>: module 'numpy' has no attribute 'x'

In [30]:
x=np.array([1,2,3])
y=np.array([4,5,6])
import numpy as np
d_1=np.subtract(x,y)
d_2=d_1[0]*d_1[0]+d_1[1]*d_1[1]+d_1[2]*d_1[2]
d_3=np.sqrt(d_2)
#linalg.norm(x-y)
print(d_1)
print(d_2)
print(d_3)


[-3 -3 -3]
27
5.196152422706632


In [25]:
x=[1,10,1]
y=[1,2,1]
import numpy as np
x-y

<class 'TypeError'>: unsupported operand type(s) for -: 'list' and 'list'

A space is formed using vectors called the vector space which is associated with two operations namely vector addition and scalar multiplication