# Matrix decomposition
Breaking a matrix into product of simpler matrices is termed as matrix decomposition

## LU Decomposition
- Also known as lower-upper decomposition
- A matrix $M$ is represented as a product of lower triangular and upper triangular matrix.
$$M=LU$$
- It is very much useful in handling problems in numerical linear algebra.
- Gaussian elimination method can be implemented here.
- it can be obtained from noninvertible or singular matrices, and from non-square matrices.
- For example,
$$\begin{bmatrix}2&2\\ 6&8\end{bmatrix}=\begin{bmatrix}1&0\\ 3&1\end{bmatrix}\begin{bmatrix}2&1\\ 0&5\end{bmatrix}$$
## LU Decomposition algorithm
- Matrix M is given.
- Write $M=IM$
- Apply gaussian elimination, where one has to obtain a triangular matrix after elementary operations on $M$.
- Do the same operations in $I$ to get a lower triangular matrix.
- For example,
$$\begin{bmatrix}2&2\\ 6&8\end{bmatrix}=\begin{bmatrix}1&0\\ 0&1\end{bmatrix}\begin{bmatrix}2&2\\ 6&8\end{bmatrix}=\begin{bmatrix}1&0\\ -3&1\end{bmatrix}\begin{bmatrix}2&2\\ 0&2\end{bmatrix}\text{  }R_2 \leftarrow R_2-2R_1$$
- scipy library in python can be used for finding LU decomposition.

In [28]:
import numpy as np
from scipy.linalg import lu
A = np.array([[2, 1, 1, 0],
              [4, 3, 3, 1],
              [8, 7, 9, 5],
              [6, 7, 9, 8]])
P,L,U= lu(A)
P # pivot matrix

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

## QR Decomposition
- A matrix M is represented as a product of an orthhogonal matrix $Q$ and an upper triangular matrix $R$.
- So it is also called QU decomposition.
- we treat $Q$ as a special kind of composition of orthonormal vectors. ($QQ^T=I$)
- Let's visit some more conceps from Basis.

## Orthogonal basis
- Recall that a LI subset spanning the whole vector space is called a basis.
- Orthogonal basis as the name suggests is a basis with an extra property that the vectors present in it are orthogonal to each other.
- A basis is said to be orthogonal if every member in the basis give inner product zero.

## Orthonormal basis
- An **orthogonal basis** is said to be orthonormal if every member in the basis are of unit length.
- We already know unit vector along $v$ is given by $\hat{v}=\frac{v}{||v||}$, so using this fact we can justify that, every orthogonal basis can be made an orthonormal basis.
- We denote matrices of these sets as $Q$ and a result associated is $QQ^T=I$ even though they are not square matrices.
- Notice that it is easier to find an othonormal basis if a orthogonal basis is given, what about constucting a orthogonal matrix from a simple basis? or why do we even need it?
- Basis are said to be computationally efficient and of good use as well as visualize, aprt from it there are wide applications of these basis are orthogonal/orthonormal.
- Grahm Schmidt orthogonalization is a process to construct a orthogonal basis from any basis set.

In [24]:
# findig 
import numpy as np
x, y = np.array([[3],[4],[0]]), np.array([[-4],[3],[2]])

# euclidean norm of x and y
x_norm = np.linalg.norm(x, 2)
y_norm = np.linalg.norm(y, 2)

# normalized x or unit vector
x_unit = x * (1/x_norm)  
y_unit = y * (1/y_norm)  
print(f'Euclidean norm of x:\n{x_norm}\n')
print(f'Euclidean norm of y:\n{y_norm}\n')

print(f'Normalized x:\n{x_unit}\n')
print(f'Normalized y:\n{y_unit}')


Euclidean norm of x:
5.0

Euclidean norm of y:
5.385164807134504

Normalized x:
[[0.6]
 [0.8]
 [0. ]]

Normalized y:
[[-0.74278135]
 [ 0.55708601]
 [ 0.37139068]]


In [25]:
print(f'Euclidean norm of normalized x:\n{np.round(np.linalg.norm(x_unit, 2),1)}\n')
print(f'Euclidean norm of normalized y:\n{np.round(np.linalg.norm(y_unit, 2),1)}')


Euclidean norm of normalized x:
1.0

Euclidean norm of normalized y:
1.0


In [26]:


print(f'Inner product normalized vectors:\n{np.round(x_unit.T @ y_unit,1)}\n')
print(f'Inner product normalized x with itself:\n{np.round(x_unit.T @ x_unit,1)}\n') 
print(f'Inner product normalized y with itself:\n{np.round(y_unit.T @ y_unit,1)}') 


Inner product normalized vectors:
[[-0.]]

Inner product normalized x with itself:
[[1.]]

Inner product normalized y with itself:
[[1.]]


# Grahm schimdt orthogonalization
It is a tool for finding an orthogonal basis form any other basis.
**Algorithm**
- Basis $B=\{v_1,v_2,\cdots v_m\}$ is given.
- $u_1=\frac{v_1}{||v_1||}$
- $u_2=v_2-\frac{<u_1,v_2>}{||u_1||}u_1$
- $\cdots$
- $u_k=v_{k}-\frac{<u_{k-1},v_{k}>}{||u_{k-1}||}u_{k-1}$
- The resultant set $B'=\{u_1,u_2,\cdots ,u_m\}$ is an orthogonal set.
- More precisely its an orthonormal set, so this process can also betermed as Grahm schimdt orthonormalization.
- **Note** donot be surprised to see $<u,v>=u^Tv$

In [11]:
# orthogonalization of basis {(2,4),(-4,-2)}
import numpy as np
v1=np.array([[2,4]])
v2=np.array([[-4,2]])
if np.inner(v1,v2)==0:
    print('orthogonal vectors')
else: print('not orthogonal') 
nom_v1=np.linalg.norm(v1,2)
nom_v2=np.linalg.norm(v2,2)
u1=(1/nom_v1)*v1
u2=(1/nom_v1)*v1
print('the orthonormal set is:',u1,u2)

orthogonal vectors
the orthonormal set is: [[0.4472136  0.89442719]] [[0.4472136  0.89442719]]


In [22]:
np.linalg.norm(u1,2)

1.0

In [23]:
np.linalg.norm(u2,2)

1.0

In [30]:
# orthogonarmalization of basis {(2,4),(-4,-2)}
import numpy as np
v1=np.array([[2,4]])
v2=np.array([[-4,2]])
if np.inner(v1,v2)==0:
    print('orthogonal vectors')
else: print('not orthogonal') 
nom_v1=np.linalg.norm(v1,2)
nom_v2=np.linalg.norm(v2,2)
u1=(1/nom_v1)*v1
u2=v2-np.inner(v2,u1)*(1/nom_v1)*v1
print('the orthonormal set is:',u1,u2)
# find u1=v1/v1 norm
#u2=v2-inner (v2,v1)v1


orthogonal vectors
the orthonormal set is: [[0.4472136  0.89442719]] [[-4.  2.]]


# QR Decomposition Algorithm
It is related with the Gram schimdt process.
