# Eigen values, Eigen vectors, Eigen space

# Eigen values
- A scalar (or factor instead) say $\lambda$ is an eigen value if $T(x)=\lambda x$
- Intutively a scaling factor is enough to describe a linear transform, then it is called an eigen value.
- As the discussion is more calculative, we need matrices into picture to make the problem of finding eigen value as a problem of finding solution of an equation.
- Let $A$ be a square matrix, and $I$ be the identity matrix then the eigen values $\lambda$ of $A$ are the roots of the equation $\text{det}(A-\lambda I)=0$ 
- $\text{det}(A-\lambda I)=0$ is called the characteristic equation, and so the roots are called characteristics root.
- Spectral values, latent roots, eigen values mean the same thing.
- Eigen value of $m\times m$ is $m$ in numbers except for multiplicity.
- The product of eigen values gives the determinant of matrix.
- The sum of eigen values gives the trace of matrix.

## Finding eigen value 
- Example $A=\begin{pmatrix}1&3\\ 4&2\end{pmatrix}$
$$|A-\lambda I|=0$$
or,
$$\begin{vmatrix}1&3\\ 4&2\end{vmatrix}-\lambda \begin{vmatrix}1&0\\ 0&1\end{vmatrix}=0$$
or,
$$\begin{vmatrix}1-\lambda &3\\ 4&2-\lambda\end{vmatrix}=0$$
or,
$$(1-\lambda)(2-\lambda)-3\cdot 4 =0$$
$$2-3\lambda+{\lambda}^2-12 =0$$
$${\lambda}^2-3\lambda-10 =0$$
$${\lambda}^2-5\lambda+2\lambda-10 =0$$
$${\lambda}(\lambda-5)+2(\lambda-5) =0$$
$${(\lambda+2)}(\lambda-5) =0$$
So, finally we have $\lambda=-2,5$, or we just write that the eigen values are $\lambda_1=-2,\lambda_2=5$






In [1]:
# find the eigen values of [1,3],[4,2]
import numpy as np
A=np.array([[1,3],
            [4,2]])
I=np.identity(2)
#np.linalg.eig(A)
val,vec=np.linalg.eig(A)

In [2]:
val

array([-2.,  5.])

In [3]:
vec

array([[-0.70710678, -0.6       ],
       [ 0.70710678, -0.8       ]])

## Eigen vectors
- Let $\lambda$ be an eigen vector, then the null space of $A-\lambda I$ is the eigen vector for the eigen value $\lambda$ 

From the previous example we have eigen values of $A=\begin{pmatrix}1&3\\ 4&2\end{pmatrix}$ as $-2,5$
- now we compute eigen vectors as solution of:
$(A-\lambda I) x=\begin{pmatrix}1-\lambda&3\\ 4&2-\lambda\end{pmatrix}\begin{pmatrix}x_1\\ x_2\end{pmatrix}=\begin{pmatrix}0\\ 0\end{pmatrix}$
- now, we have to put $\lambda=-2$
- We now have $\begin{pmatrix}1+2&3\\ 4&2+2\end{pmatrix}\begin{pmatrix}x_1\\ x_2\end{pmatrix}=\begin{pmatrix}0\\ 0\end{pmatrix} \implies \begin{pmatrix}3&3\\ 4&4\end{pmatrix}\begin{pmatrix}x_1\\ x_2\end{pmatrix}=\begin{pmatrix}0\\ 0\end{pmatrix}\implies (x_1,x_2)=(1,-1)$
- now, we have to put $\lambda=5$ to get $\begin{pmatrix}1-5&3\\ 4&2-5\end{pmatrix}\begin{pmatrix}x_1\\ x_2\end{pmatrix}=\begin{pmatrix}0\\ 0\end{pmatrix} \implies \begin{pmatrix}-4&3\\ 4&-3\end{pmatrix}\begin{pmatrix}x_1\\ x_2\end{pmatrix}=\begin{pmatrix}0\\ 0\end{pmatrix} \implies (x_1,x_2)=(3,4)$
- The eigen vectors are $(1,-1),(3,4)$

In [6]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Eigen decomposition
- It is the process of obtaining the most simpler matrix $D$ called the diagonal matrix for a matrix $A$.
- It is popularly known as diagonalization process istead of eigen decomposition.
- $A=XDX^{-1}$ is the required decompposition.
- Here, $D$ is the diagonal matrix for A.
- $X$ is the matrix of the eigen vectors of $A$.

**For example** we need to diagonalize the matrix
$A=\begin{pmatrix}1&3\\ 4&2\end{pmatrix}$ and as we know the eigen vectors are $(1,-1),(3,4)$
so we have, $X=\begin{pmatrix}1&3\\-1&4\end{pmatrix}$.

Now we need inverse of $X$ to be muliplied to get the diagonal matrix as $\begin{pmatrix}1&3\\ 4&2\end{pmatrix}$ and as we know the eigen vectors are $(1,-1),(3,4)$
so we have, $D=\begin{pmatrix}-2&0\\0&5\end{pmatrix}$

In [19]:
import numpy as np

# Step 1: Defining the matrix
A = np.array([[1, 3],
              [4, 2]])
# Step 2: Finding eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Step 3: Check if the matrix is diagonalizable
if not np.all(np.iscomplex(eigenvalues)):
    # Step 4: Create the diagonal matrix
    D = np.diag(eigenvalues)

    # Step 5: Find the inverse of the eigenvector matrix
    P_inv = np.linalg.inv(eigenvectors)

    # Step 6: Diagonalize the matrix
    diagonalized_matrix = np.dot(P_inv, np.dot(A, eigenvectors))

    # Printing the diagonalized matrix
    print("Diagonalized Matrix:")
    print(diagonalized_matrix)
else:
    print("Matrix is not diagonalizable.")


Diagonalized Matrix:
[[-2.0000000e+00  4.4408921e-16]
 [ 0.0000000e+00  5.0000000e+00]]
