# Matrices
These are rectangular array of objects.
- Terms like element,entries,etc. refer to the objects of the matrix.
- Matrix has rows and columns.
- rows represent vectors in horizontal sense.
- columns represent the vectors in vertical sense.
- A matrix having $n\text{ columns and }m \text{ rows }$is said to be of order $m\times n$.
- An entry of a matrix is always seen as $a_{ij}$ where $i$ is row number $j$ is column number.
- If the number of rows and columns in a matrix are same then it is called a square matrix.
- Square matrix are very much significant in linear algebra.
$$A=\begin{pmatrix}
a_{11} & a_{12}&\cdots & a_{1n}\\
a_{21} & a_{22}&\cdots & a_{2n}\\
\cdots\\
a_{n1} & a_{n2}&\cdots & a_{nn}\\
\end{pmatrix}$$


In [2]:
# printing a matrix
import numpy as np
np.array([[1,2],[4,5]]) #array() returns us matrix row-wise array([1st row],[2nd row], and so on...)

array([[1, 2],
       [4, 5]])

In [4]:
import numpy as np
np.array([[1],[5]]) 
# one can play with this to form matrices of different orders

array([[1],
       [5]])

In [11]:
#printing specific entry of an array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a[1][1] #a_ij=a[i-+][j+1] for python, be careful!! so it starts indexing from 0, but we prefer from 1

5

In [15]:
#no of rows/columns
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape #notice that this .shape gives the order of our matrix

(2, 3)

## Multiplication of matrices
- Let $A=[a_{ij}]_{m\times n}$ and $B=[b_{ij}]_{n\times p}$ then 
$$A\times B=C=[c_{ij}]_{m\times p}=\left[\sum_{k=1}^{n}{a_{ik}}+b_{kj}\right]_{m\times p}$$
- Matrix multiplication is valid for matrices if number of rows in one matrix is same as no of columns of another matrix.
- Square matrices of same order can be treated with matrix multiplicatin and the resultant matrix is also square matrix of same order.
- Matrices are often linked to linear transformation, system of equation.
- Although mmatrix multiplication is very much calculative, but still it has a lot to do with geometric aspects. Well known Operations such as rotation, inversion,etc. can be identified as a matrix multiplication.

### Properties
- $AB\ne BA$ always!!
- $A(BC)=(AB)C$
- $A(B+C)=AB+AC$
- $\alpha AB=(\alpha A)B$
- $(AB)^T=B^TA^T$

In [64]:
# Matrix multiplication
A=[[1,2,3],[4,5,6]]
B=[[1,4],[1,2],[2,1]]
C=[[0,0],[0,0]]
for i in range (len(A)): # A is of length 2
    for j in range (len(B[0])): #B[0] is of length 3
        for k in range (len(B)): # defining k to store values in c
            C[i][j]=C[i][j]+A[i][k]*B[k][j] #storing cij valu as a sum of product of columns of a with rows of b
print(C)

[[9, 11], [21, 32]]


In [63]:
# Matrix muliplication with numpy
# we would take matrices of order such that no of rows of first is same as no of columns in second matrix
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,4],[1,2],[2,1]])
#print(A)
#print(B)
C=A@B
print(C)
print(np.dot(A,B))

[[ 9 11]
 [21 32]]
[[ 9 11]
 [21 32]]


**A special kind of matrix multiplication**

In matrices we can define multiplication such that entries in first matrix is multiplied with corrosponding entry of matrix called the component multiplication

$$[a_{ij}]\times [b_{ij}]=[a_{ij}b_{ij}]$$

In [12]:
#Componentwise matrix multiplication
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,4,1],[2,2,1]])
C=np.array([[0,0,0],[0,0,0]])
for i in range (len(A)):
    for j in range (len(A[0])):
        C[i][j]=A[i][j]*B[i][j]
print(C)
# in numpy we compute CWMM with A*B
print(A*B)

[[ 1  8  3]
 [ 8 10  6]]
[[ 1  8  3]
 [ 8 10  6]]


# Common Notions
- **Diagonal entries** of a square matrix refers to the entries $a_{ii}$ often termed as main diagonal or leading diagonal.
- **Anti-diagonal** of a square matrix refers to the non-main-diagonal 
- **Determinant** of a square matrix is obtained by sum and product of entries in a specific fashion.
- **Trace** is the sum of diagonal entries of a matrix.

# Types of square matrix
## 1. Transpose matrix
The operation of interchanging rows and columns of a matrix mutually is called transposing. Often denoted as $A^T$
For example the transpose of matrix $(1~2~3)$ is $\begin{pmatrix} 1\\2\\3\end{pmatrix}$

- Transposing is not limited to square matrices, we can transpose all kind of matrices.
## 2. Identity Matrix
The identity matrix often denoted as $I$ is a square matrix with diagonal entries as $1$ rest all zero.
$$I_{3\times 3}=\begin{pmatrix}1&0&0\\0&1&0\\0&0&1\end{pmatrix}_{3\times{3}}$$
- multiplying a matrix with identity matrix never alters the matrix.
- multiplying a matrix with its invers results in identity matrix
## 3. Inverse Matrix
Let $A$ be a square matrix then the inverse of $A$ is denoted as $A^{-1}$ is the matrix which when multiplied with $A$ gives the identity matrix.
**Note:** inverse of a matrix always exist when we have a singular matrix.
## 4. Singular/Non-singular matrix
A square matrix is said to be singular if its determinant is zero, else it is non singular.
## 5. Symmetric matrix
A square matrix is said to be symmetric if its transpose is same as the matrix.

$A$ is symmetric iff $A^T=A$
## 6. Skew-symmetric matrix
A square matrix is said to be skew-symmetric if its transpose is same as the matrix and only differ by a negative sign.

$A$ is symmetric iff $A^T=-A$
## 7. Triangular matrix
A matrix is said to be triangular if entries above or below the leading diagonal are zero.
- If entries above main diagonal are zero we call it lower triangular else upper triangular.
## 8. Diagonal matrix
A matrix whose entries are zero except the main diagonal entries is called a diagonal matrix.
## 9. Scalar matrix
A matrix identifed as a scalar multiple of identity matrix is called as a scalar matrix.
## 10. zero matrix
A matrix with all entries as zero is a zero matrix.
- multiplying a matrix with the zero matrix gives zero matrix.
- adding zero matrix with a matrix returns the matrix itself.
11. Orthogonal matrix
A matrix is orthogonal if $A^T=a^{-1}$ or equivalently $AAT=I$
12. Unitary matrix
A matrix is unitary if $A^*=a^{-1}$ or equivalently $AA^*=I$

# Matrix addition
In order to add matrices, matrices has to be of same order, we just add each entry of first matrix with corresponding entry of the other matrix.

In [14]:
#Adding matrices
a=[[1,2],[3,4]]
b=[[2,1],[2,2]]
c=[[0,0],[0,0]]
for i in range (len(a)):
    for j in range (len(a[0])):
                    c[i][j]=a[i][j]+b[i][j]
print(c)

[[3, 3], [5, 6]]


In [ ]:
# finding transpose, inverse is left as an exercise to reader!!

# Matrix-scalar multiplication
Matrix-scalar multiplication is the operation of multiplying each entry of matrix with scalar.

$$\alpha [a_{ij}]=[\alpha a_{ij}]$$

In [2]:
# multiplying matrix [[1,2],[3,4]] with 5
a=[[1,2],[3,4]]
b=5
for i in range (len(a)):
    for j in range (len(a[0])):
        a[i][j]=b*a[i][j]
print(a)

[[5, 10], [15, 20]]


In [3]:
# multiplying matrix [[1,2],[3,4]] with 5 in numpy
import numpy as np
a=np.array([[1,2],[3,4]])
b=5
c=b*a
print(c)

[[ 5 10]
 [15 20]]


## Rank of matrix
- Rank of a matrix is defined as the total number of linearly independent rows or columns in the matrix.
- Finding rank of matrix computationally is more specific to solving system of linear equations.
- its also possible that we just check the row reduced echolon form and then tell the rank.

# Matrix norm
- One can define norm in matrix in multiple ways.
- Frobenius norm, max norm,spectral norm are most widely used.

## Frobenius norm
- Often denoted as $||A||_F$
- It is calculated by taking the sum of squares of all the entries of the matrix and then its squareroot.
- Let $A_{m\times n}$ then the Frobenius norm is:
$$||A||_F=\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^2$$

In [23]:
# Find the frobenius norm of the matrix [[1,2],[3,4]]
a=[[1,2,3],[3,4,5]]
b=0
for i in range(len(a)):
    for j in range(len(a[0])):
        b=b+a[i][j]*a[i][j]
#print(b)
c=pow(b,0.5)
print("The Frobenius norm is:",c)

The Frobenius norm is: 8.0


In [31]:
# Find the frobenius norm of the matrix [[1,2],[3,4]] using numpy
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.linalg.norm(a,'fro')
print("The Frobenius norm using numpy is:",b)

The Frobenius norm using numpy is: 8.0


## Max norm
- Often denoted as $||A||_{max}$ or $||A||_{\infty}$
- It is calculated by taking the sum of absolute values of each rows and then the maximum among them.
- Let $A_{m\times n}$ then the Max norm is:
$$||A||_{Max}=Max_{1\le i\le n}\sum_{j=1}^{n}|a_{ij}|$$

In [5]:
# Find the max norm of the matrix [[1,2],[3,4]]
a=[[1,2,3],[3,4,5]]
b=[0,0]
for i in range(len(a)):
    for j in range(len(a[0])):
        b[i]=b[i]+abs(a[i][j])
#print(b)
c=max(b)
print("The Max norm is:",c)

The Max norm is: 12


In [2]:
# Find the max norm of the matrix [[1,2],[3,4]] using numpy
import numpy as np
a=[[1,2,3],[3,4,5]]
c=np.linalg.norm(a,np.inf)
print("The Max norm is:",c)

The Max norm is: 12.0


## Spectral norm

- The spectral norm of a matrix is defined as:
$$||A||_2=Max_{x}\frac{||Ax||}{||A||}$$
- The norm signifies the maximum extent to which a matrix can strech a vector.

In [6]:
# Spectral norm of [1,2,3],[3,4,5]
import numpy as np
a=[[1,2,3],[3,4,5]]
c=np.linalg.norm(a,2)
print("The Max norm is:",c)

The Max norm is: 7.97638869424527
